[mypy]
python_version = 3.12
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false

[mypy-openpyxl.*]
ignore_missing_imports = true

[mypy-pandas.*]
ignore_missing_imports = true

[mypy-numpy.*]
ignore_missing_imports = true

[mypy-numpy]
ignore_errors = true

[mypy-faker.*]
ignore_missing_imports = true

[mypy-pytest.*]
ignore_missing_imports = true
