"""Unit tests for OpenAI management summary generation."""

from unittest.mock import MagicMock, patch

import pytest

from src.config.settings import get_settings
from src.services.ai_service import AISummaryError, generate_management_summary


@pytest.fixture(autouse=True)
def clear_settings_cache():
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


def test_openai_summary_without_key_raises(monkeypatch):
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    get_settings.cache_clear()
    with pytest.raises(AISummaryError, match="OpenAI API key required"):
        generate_management_summary({}, [], {}, {}, provider="openai", openai_api_key="")


def test_openai_summary_uses_api_response(monkeypatch):
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setenv("OPENAI_MODEL", "gpt-4o-mini")

    mock_message = MagicMock()
    mock_message.content = "# OpenAI Summary\n\nGenerated by model."

    mock_choice = MagicMock()
    mock_choice.message = mock_message

    mock_response = MagicMock()
    mock_response.choices = [mock_choice]

    mock_client = MagicMock()
    mock_client.chat.completions.create.return_value = mock_response

    with patch("openai.OpenAI", return_value=mock_client):
        text = generate_management_summary(
            {"total_inventory_value": 1000},
            [],
            {"recommended_count": 1, "total_net_benefit": 250},
            {"candidate_count": 2, "total_recovery": 500},
            provider="openai",
        )

    assert text == "# OpenAI Summary\n\nGenerated by model."
    mock_client.chat.completions.create.assert_called_once()
    call_kwargs = mock_client.chat.completions.create.call_args.kwargs
    assert call_kwargs["model"] == "gpt-4o-mini"
    user_content = call_kwargs["messages"][1]["content"]
    assert "total_inventory_value" in user_content
    assert "1000" in user_content


def test_openai_summary_raises_on_api_error(monkeypatch):
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")

    mock_client = MagicMock()
    mock_client.chat.completions.create.side_effect = RuntimeError("API unavailable")

    with patch("openai.OpenAI", return_value=mock_client):
        with pytest.raises(AISummaryError, match="OpenAI request failed"):
            generate_management_summary({}, [], {}, {}, provider="openai")


def test_openai_summary_accepts_runtime_api_key_override():
    mock_message = MagicMock()
    mock_message.content = "Runtime key summary."

    mock_choice = MagicMock()
    mock_choice.message = mock_message

    mock_response = MagicMock()
    mock_response.choices = [mock_choice]

    mock_client = MagicMock()
    mock_client.chat.completions.create.return_value = mock_response

    with patch("openai.OpenAI", return_value=mock_client) as mock_openai_ctor:
        text = generate_management_summary(
            {},
            [],
            {},
            {},
            provider="openai",
            openai_api_key="runtime-key",
        )

    assert text == "Runtime key summary."
    mock_openai_ctor.assert_called_once_with(api_key="runtime-key")
